export const SUB_EVENTS = [
  {
    id: 'theatre',
    name: 'Theatre',
    fullName: 'Voices of Power',
    tagline: 'Where Words Become Weapons',
    description:
      'A powerful theatre/natak performance exploring science, war, and humanity. Bring your story to the Multipurpose Hall stage.',
    venue: 'Multipurpose Hall, A-Block',
    icon: '🎭',
    color: '#DC2626',
    gradientFrom: '#7F1D1D',
    gradientTo: '#DC2626',
    maxTeamSize: 10,
    minTeamSize: 3,
    isTeamEvent: true,
    registrationFields: [
      'team_name',
      'team_leader_name',
      'team_leader_roll',
      'team_leader_course',
      'team_leader_year',
      'team_leader_phone',
      'team_leader_email',
      'team_members',
      'performance_title',
      'performance_duration',
    ],
  },
  {
    id: 'science_slam',
    name: 'Science Slam',
    fullName: 'Whispers of Hope, Suffering & Survival',
    tagline: 'Your Voice. Your Science. Your War.',
    description:
      'Express through monoact, poetry, or open mic. Tell the story of science in conflict — hope, suffering, and survival.',
    venue: 'Multipurpose Hall, A-Block',
    icon: '🎤',
    color: '#D97706',
    gradientFrom: '#78350F',
    gradientTo: '#D97706',
    maxTeamSize: 1,
    minTeamSize: 1,
    isTeamEvent: false,
    registrationFields: [
      'participant_name',
      'roll_number',
      'course',
      'year_of_study',
      'department',
      'phone',
      'email',
      'performance_type',
      'performance_title',
    ],
  },
  {
    id: 'wartech_quiz',
    name: 'WarTech Quiz',
    fullName: 'Science in Conflict',
    tagline: 'Test Your Knowledge on the Battlefield of Science',
    description:
      'Rounds: Weapons & Chemistry · Technology in War · Environmental Impact · Medical & Forensic Science · Innovation Under Pressure',
    venue: 'Moot Court, A-Block',
    icon: '🧪',
    color: '#3B82F6',
    gradientFrom: '#1E3A5F',
    gradientTo: '#3B82F6',
    maxTeamSize: 3,
    minTeamSize: 2,
    isTeamEvent: true,
    registrationFields: [
      'team_name',
      'team_leader_name',
      'team_leader_roll',
      'team_leader_course',
      'team_leader_year',
      'team_leader_phone',
      'team_leader_email',
      'member_2_name',
      'member_2_roll',
      'member_3_name',
      'member_3_roll',
    ],
  },
  {
    id: 'poster',
    name: 'Poster Making',
    fullName: 'Echoes of War, Eyes of Science',
    tagline: 'Paint the Unseen Battlefield',
    description:
      'Create a powerful poster on themes: Science Under Shadow of War · When Innovation Meets Destruction · War vs Humanity: A Scientific Perspective',
    venue: 'Multipurpose Hall, A-Block',
    icon: '🎨',
    color: '#7C3AED',
    gradientFrom: '#3B0764',
    gradientTo: '#7C3AED',
    maxTeamSize: 2,
    minTeamSize: 1,
    isTeamEvent: false,
    registrationFields: [
      'participant_name',
      'roll_number',
      'course',
      'year_of_study',
      'department',
      'phone',
      'email',
      'poster_theme',
    ],
  },
]

export function getSubEvent(id) {
  return SUB_EVENTS.find((e) => e.id === id) ?? null
}
