export const SUB_EVENTS = [
  {
    id: 'war_room_debate',
    name: 'The War Room Debate',
    fullName: 'The War Room Debate',
    tagline: 'Three Perspectives. One Conflict.',
    description:
      'Debate tracks: Scientists, UN Delegates, and Policy Makers. Choose your position and defend your perspective in the war room.',
    venue: 'Multipurpose Hall, A-Block',
    icon: '🗣️',
    color: '#DC2626',
    gradientFrom: '#7F1D1D',
    gradientTo: '#DC2626',
    maxTeamSize: 1,
    minTeamSize: 1,
    isTeamEvent: false,
    registrationFields: [
      'participant_name',
      'roll_number',
      'course',
      'year_of_study',
      'department',
      'phone',
      'email',
      'debate_topic',
    ],
  },
  {
    id: 'science_slam',
    name: 'Science Slam',
    fullName: 'Whispers of Hope, Suffering & Survival',
    tagline: 'Your Voice. Your Science. Your War.',
    description:
      'Express through monoact, poetry, or open mic. Tell the story of science in conflict — hope, suffering, and survival.',
    venue: 'Multipurpose Hall, A-Block',
    icon: '🎤',
    color: '#D97706',
    gradientFrom: '#78350F',
    gradientTo: '#D97706',
    maxTeamSize: 1,
    minTeamSize: 1,
    isTeamEvent: false,
    registrationFields: [
      'participant_name',
      'roll_number',
      'course',
      'year_of_study',
      'department',
      'phone',
      'email',
      'performance_type',
      'performance_title',
    ],
  },
  {
    id: 'wartech_quiz',
    name: 'WarTech Quiz',
    fullName: 'Science in Conflict',
    tagline: 'Test Your Knowledge on the Battlefield of Science',
    description:
      'Rounds: Weapons & Chemistry · Technology in War · Environmental Impact · Medical & Forensic Science · Innovation Under Pressure',
    venue: 'Moot Court, A-Block',
    icon: '🧪',
    color: '#3B82F6',
    gradientFrom: '#1E3A5F',
    gradientTo: '#3B82F6',
    maxTeamSize: 1,
    minTeamSize: 1,
    isTeamEvent: false,
    registrationFields: [
      'participant_name',
      'roll_number',
      'course',
      'year_of_study',
      'department',
      'phone',
      'email',
    ],
  },
  {
    id: 'poster',
    name: 'Poster Making',
    fullName: 'Echoes of War, Eyes of Science',
    tagline: 'Paint the Unseen Battlefield',
    description:
      'Create a powerful poster on themes: Science Under Shadow of War · When Innovation Meets Destruction · War vs Humanity: A Scientific Perspective',
    venue: 'Multipurpose Hall, A-Block',
    icon: '🎨',
    color: '#7C3AED',
    gradientFrom: '#3B0764',
    gradientTo: '#7C3AED',
    maxTeamSize: 1,
    minTeamSize: 1,
    isTeamEvent: false,
    registrationFields: [
      'participant_name',
      'roll_number',
      'course',
      'year_of_study',
      'department',
      'phone',
      'email',
      'poster_theme',
    ],
  },
]

export function getSubEvent(id) {
  return SUB_EVENTS.find((e) => e.id === id) ?? null
}
