export const SUB_EVENTS = [
  {
    id: 'war_room_debate',
    name: 'The War Room - Debate Battle',
    fullName: 'The War Room - Debate Battle',
    tagline: 'Three Perspectives. One Conflict.',
    description:
      'Debate tracks: Scientists, UN Delegates, and Policy Makers. Choose your position and defend your perspective in the war room.',
    venue: 'Multipurpose Hall, A-Block',
    icon: '🗣️',
    color: '#DC2626',
    gradientFrom: '#7F1D1D',
    gradientTo: '#DC2626',
    maxTeamSize: 1,
    minTeamSize: 1,
    isTeamEvent: false,
    registrationFields: [
      'participant_name',
      'roll_number',
      'course',
      'year_of_study',
      'department',
      'phone',
      'email',
      'debate_topic',
    ],
    rules: [
      'Individual participation only — no teams.',
      'Each participant must choose one debate track: Scientist, UN Delegate, or Policy Maker.',
      'Speaking time per round: maximum 3 minutes for arguments, 1 minute for rebuttals.',
      'Arguments must be backed by facts; personal attacks or offensive language will lead to disqualification.',
      'Mobile phones must be switched off or on silent during the debate.',
      'The judges\' decision is final and binding.',
      'Participants must report to the venue at least 15 minutes before the scheduled start time.',
    ],
  },
  {
    id: 'science_slam',
    name: 'Science Slam',
    fullName: 'Whispers of Hope, Suffering & Survival',
    tagline: 'Your Voice. Your Science. Your War.',
    description:
      'Express through monoact, poetry, or open mic. Tell the story of science in conflict — hope, suffering, and survival.',
    venue: 'Multipurpose Hall, A-Block',
    icon: '🎤',
    color: '#D97706',
    gradientFrom: '#78350F',
    gradientTo: '#D97706',
    maxTeamSize: 1,
    minTeamSize: 1,
    isTeamEvent: false,
    registrationFields: [
      'participant_name',
      'roll_number',
      'course',
      'year_of_study',
      'department',
      'phone',
      'email',
      'performance_type',
      'performance_title',
    ],
    rules: [
      'Individual participation only — solo performances.',
      'Eligible formats: monoact, spoken word poetry, or open mic.',
      'Maximum performance duration: 5 minutes. Exceeding the time limit will result in score deduction.',
      'Content must be original and relate to the theme: Science in Conflict.',
      'Props, costumes, and backing tracks are permitted; prior arrangement is required for audio/video support.',
      'No offensive, obscene, or politically sensitive content is permitted.',
      'The judging panel\'s decision is final.',
    ],
  },
  {
    id: 'wartech_quiz',
    name: 'WarTech Quiz',
    fullName: 'Science in Conflict',
    tagline: 'Test Your Knowledge on the Battlefield of Science',
    description:
      'Rounds: Weapons & Chemistry · Technology in War · Environmental Impact · Medical & Forensic Science · Innovation Under Pressure',
    venue: 'Moot Court, A-Block',
    icon: '🧪',
    color: '#3B82F6',
    gradientFrom: '#1E3A5F',
    gradientTo: '#3B82F6',
    maxTeamSize: 1,
    minTeamSize: 1,
    isTeamEvent: false,
    registrationFields: [
      'participant_name',
      'roll_number',
      'course',
      'year_of_study',
      'department',
      'phone',
      'email',
    ],
    rules: [
      'Individual participation only.',
      'The quiz consists of multiple rounds: Weapons & Chemistry, Technology in War, Environmental Impact, Medical & Forensic Science, and Innovation Under Pressure.',
      'No electronic devices (phones, smartwatches, tablets) are permitted during the quiz.',
      'Answers must be submitted within the time limit announced for each question.',
      'In case of a tie, a rapid-fire tiebreaker round will be conducted.',
      'Once an answer is submitted, it cannot be changed.',
      'The quiz master\'s decision is final in all matters.',
    ],
  },
  {
    id: 'poster',
    name: 'Poster Making',
    fullName: 'Echoes of War, Eyes of Science',
    tagline: 'Paint the Unseen Battlefield',
    description:
      'Create a powerful poster on themes: Science Under Shadow of War · When Innovation Meets Destruction · War vs Humanity: A Scientific Perspective',
    venue: 'Multipurpose Hall, A-Block',
    icon: '🎨',
    color: '#7C3AED',
    gradientFrom: '#3B0764',
    gradientTo: '#7C3AED',
    maxTeamSize: 1,
    minTeamSize: 1,
    isTeamEvent: false,
    registrationFields: [
      'participant_name',
      'roll_number',
      'course',
      'year_of_study',
      'department',
      'phone',
      'email',
      'poster_theme',
    ],
    rules: [
      'Individual participation only.',
      'Poster size: A2 (420 × 594 mm). Participants must bring their own art supplies.',
      'Choose one theme: Science Under Shadow of War · When Innovation Meets Destruction · War vs Humanity: A Scientific Perspective.',
      'Only hand-drawn / hand-painted posters are allowed; no digital prints or pre-drawn sketches.',
      'Duration: 2 hours. Work must be completed on-site within the allotted time.',
      'Posters must include the participant\'s name, roll number, and chosen theme on the reverse side.',
      'Judging criteria: relevance to theme, creativity, visual impact, and clarity of message.',
      'The judges\' decision is final.',
    ],
  },
]

export function getSubEvent(id) {
  return SUB_EVENTS.find((e) => e.id === id) ?? null
}
